// @generated THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Types from '../../../../shared/model/models.gen';

export type RepoListQueryVariables = Types.Exact<{
  login: Types.Scalars['String']['input'];
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  privacy?: Types.InputMaybe<Types.RepositoryPrivacy>;
}>;


export type RepoListQuery = { user?: { repositories: { totalCount: number, nodes?: Array<{ name: string, stargazerCount: number, url: any, commitComments: { nodes?: Array<{ createdAt: any } | null> | null } } | null> | null, pageInfo: { startCursor?: string | null, endCursor?: string | null } } } | null };
