query repoList($login: String!, $first: Int, $privacy: RepositoryPrivacy) {
  user(login: $login) {
    repositories(first: $first, privacy: $privacy) {
      nodes {
        name
        stargazerCount
        commitComments(last: 1) {
          nodes {
            createdAt
          }
        }
        url
      }
      totalCount
      pageInfo {
        startCursor
        endCursor
      }
    }
  }
}
