// @generated THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Types from '../../../../shared/model/models.gen';

export type RepoListQueryVariables = Types.Exact<{
  login: Types.Scalars['String']['input'];
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  privacy?: Types.InputMaybe<Types.RepositoryPrivacy>;
}>;


export type RepoListQuery = { __typename?: 'Query', user?: { __typename?: 'User', repositories: { __typename?: 'RepositoryConnection', totalCount: number, nodes?: Array<{ __typename?: 'Repository', name: string, stargazerCount: number, url: any, commitComments: { __typename?: 'CommitCommentConnection', nodes?: Array<{ __typename?: 'CommitComment', createdAt: any } | null> | null } } | null> | null, pageInfo: { __typename?: 'PageInfo', startCursor?: string | null, endCursor?: string | null } } } | null };
