query repoList($login: String!, $first: Int, $privacy: RepositoryPrivacy) {
  user(login: $login) {
    repositories(first: $first, privacy: $privacy) {
      nodes {
        id
        name
        stargazerCount
        pushedAt
        url
      }
      totalCount
      pageInfo {
        startCursor
        endCursor
      }
    }
  }
}
