// @generated THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Types from '../../../../shared/model/models.gen';

export type RepoListQueryVariables = Types.Exact<{
  login: Types.Scalars['String']['input'];
  first?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  privacy?: Types.InputMaybe<Types.RepositoryPrivacy>;
}>;


export type RepoListQuery = { readonly __typename?: 'Query', readonly user?: { readonly __typename?: 'User', readonly repositories: { readonly __typename?: 'RepositoryConnection', readonly totalCount: number, readonly nodes?: ReadonlyArray<{ readonly __typename?: 'Repository', readonly id: string, readonly name: string, readonly stargazerCount: number, readonly url: any, readonly commitComments: { readonly __typename?: 'CommitCommentConnection', readonly nodes?: ReadonlyArray<{ readonly __typename?: 'CommitComment', readonly createdAt: any } | null> | null } } | null> | null, readonly pageInfo: { readonly __typename?: 'PageInfo', readonly startCursor?: string | null, readonly endCursor?: string | null } } } | null };
