fragment RepoFields on Repository {
  id
  name
  stargazerCount
  pushedAt
  url
}

query searchRepoList(
  $after: String
  $before: String
  $first: Int
  $query: String!
  $type: SearchType!
) {
  search(
    after: $after
    before: $before
    first: $first
    query: $query
    type: $type
  ) {
    nodes {
      ...RepoFields
    }
    repositoryCount
    pageInfo {
      startCursor
      endCursor
    }
  }
}
