// @generated THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Types from "../../../../shared/model/models.gen";

export type RepoFieldsFragment = {
  __typename?: "Repository";
  name: string;
  stargazerCount: number;
  commitComments: {
    __typename?: "CommitCommentConnection";
    nodes?: Array<{
      __typename?: "CommitComment";
      createdAt: any;
    } | null> | null;
  };
};

export type SearchRepoListQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  before?: Types.InputMaybe<Types.Scalars["String"]["input"]>;
  first?: Types.InputMaybe<Types.Scalars["Int"]["input"]>;
  query: Types.Scalars["String"]["input"];
}>;

export type SearchRepoListQuery = {
  __typename?: "Query";
  search: {
    __typename?: "SearchResultItemConnection";
    repositoryCount: number;
    nodes?: Array<
      | { __typename?: "App" }
      | { __typename?: "Discussion" }
      | { __typename?: "Issue" }
      | { __typename?: "MarketplaceListing" }
      | { __typename?: "Organization" }
      | { __typename?: "PullRequest" }
      | {
          __typename?: "Repository";
          name: string;
          stargazerCount: number;
          commitComments: {
            __typename?: "CommitCommentConnection";
            nodes?: Array<{
              __typename?: "CommitComment";
              createdAt: any;
            } | null> | null;
          };
        }
      | { __typename?: "User" }
      | null
    > | null;
    pageInfo: {
      __typename?: "PageInfo";
      startCursor?: string | null;
      endCursor?: string | null;
    };
  };
};
