query RepoList(
  $login: String!
  $last: Int
  $privacy: RepositoryPrivacy
  $lastComment: Int
) {
  user(login: $login) {
    repositories(last: $last, privacy: $privacy) {
      nodes {
        name
        stargazerCount
        commitComments(last: $lastComment) {
          nodes {
            createdAt
          }
          totalCount
        }
        url
      }
      totalCount
    }
  }
}
